Backported gosu and root step-down
IGNITION_UID and IGNITION_GID env vars now work like in 8.1.9+

diff --git a/7.9/Dockerfile b/7.9/Dockerfile
--- a/7.9/Dockerfile
+++ b/7.9/Dockerfile
@@ -21,6 +21,15 @@ ARG IGNITION_EDGE_ARMHF_DOWNLOAD_URL="https://files.inductiveautomation.com/rele
 ARG IGNITION_EDGE_ARMHF_DOWNLOAD_SHA256="176dc1e86f6719b80b6907ca6833ee4b83d9d1f9e7cdd2fd1dc58b9d4fd38d0a"
 ARG IGNITION_ARMHF_JRE_SUFFIX="arm32hf"
 
+# gosu Download Parameters
+ARG GOSU_VERSION="1.14"
+ARG GOSU_AMD64_DOWNLOAD_URL="https://github.com/tianon/gosu/releases/download/${GOSU_VERSION}/gosu-amd64"
+ARG GOSU_AMD64_DOWNLOAD_SHA256="bd8be776e97ec2b911190a82d9ab3fa6c013ae6d3121eea3d0bfd5c82a0eaf8c"
+ARG GOSU_ARMHF_DOWNLOAD_URL="https://github.com/tianon/gosu/releases/download/${GOSU_VERSION}/gosu-armhf"
+ARG GOSU_ARMHF_DOWNLOAD_SHA256="abb1489357358b443789571d52b5410258ddaca525ee7ac3ba0dd91d34484589"
+ARG GOSU_ARM64_DOWNLOAD_URL="https://github.com/tianon/gosu/releases/download/${GOSU_VERSION}/gosu-arm64"
+ARG GOSU_ARM64_DOWNLOAD_SHA256="73244a858f5514a927a0f2510d533b4b57169b64d2aa3f9d98d92a7a7df80cea"
+
 # Default Build Edition - FULL, EDGE
 ARG BUILD_EDITION="FULL"
 
@@ -45,6 +54,19 @@ RUN set -exo pipefail; \
         exit 1; \
     fi
 
+# Download gosu based on Detected Architecture
+RUN set -exo pipefail; \
+    dpkg_arch="$(dpkg --print-architecture | awk '{print toupper($0)}')"; \
+    download_url_env="GOSU_${dpkg_arch}_DOWNLOAD_URL"; \
+    download_sha256_env="GOSU_${dpkg_arch}_DOWNLOAD_SHA256"; \
+    if [[ -n "${!download_url_env}" ]] && [[ -n "${!download_sha256_env}" ]]; then \
+    wget -q --ca-certificate=/etc/ssl/certs/ca-certificates.crt -O "gosu" "${!download_url_env}" && \
+    echo "${!download_sha256_env}" "gosu" | sha256sum -c -; \
+    else \
+    echo "Architecture ${dpkg_arch} download targets for gosu not defined, aborting build"; \
+    exit 1; \
+    fi; \
+    chmod a+x "gosu"
 
 # Extract Installation Zip File
 RUN mkdir ignition && \
@@ -111,6 +133,7 @@ RUN mkdir ${IGNITION_INSTALL_USERHOME} && \
 COPY --chown=${IGNITION_UID}:${IGNITION_GID} --from=downloader /root/ignition ${IGNITION_INSTALL_LOCATION}
 COPY --chown=${IGNITION_UID}:${IGNITION_GID} --from=downloader /var/lib/ignition /var/lib/ignition
 COPY --chown=${IGNITION_UID}:${IGNITION_GID} --from=downloader /var/log/ignition /var/log/ignition
+COPY --from=downloader /root/gosu /usr/local/bin/
 RUN ln -s /dev/stdout /var/log/ignition/wrapper.log && \
     chown -h ${IGNITION_UID}:${IGNITION_GID} /var/log/ignition/wrapper.log
 
@@ -122,7 +145,7 @@ HEALTHCHECK --interval=10s --start-period=60s --timeout=3s \
 EXPOSE 8088 8043 8000
 
 # Launch Ignition
-USER ${IGNITION_UID}
+USER root
 WORKDIR ${IGNITION_INSTALL_LOCATION}
 
 # Update path to include embedded java install location
